name: Frontend Publish

env:
  VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Unit Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Unit Test
        run: npm run test:coverage
  publish:
    runs-on: ubuntu-latest
    needs: unit-test
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: c603b90c5fabd3b317c7a286478543ea
          projectName: axa-assignment-frontend
          directory: ./dist
